### ISSUE TITLE
snap packages need to be run as root

### ISSUE THREAD

**Issue by zigford** [JamesB192/JamesB192-overlay#1]
Thanks for making a working up to date snapd package.
It installed and I can install snap packages on my machine, however, after I have installed an app, it only works if I run it as root:

```
harrisj@spock-local ~ $ uname -a
Linux spock-local 4.17.4-gentoojesse #1 SMP Sun Jul 8 11:26:11 AEST 2018 x86_64 Intel(R) Core(TM) i5-4670 CPU @ 3.40GHz GenuineIntel GNU/Linux
harrisj@spock-local ~ $ snap version
snap    2.34
snapd   2.34
series  16
gentoo  -
kernel  4.17.4-gentoojesse
harrisj@spock-local ~ $ snap run hello-world
need to run as root or suid
harrisj@spock-local ~ $ 
harrisj@spock-local ~ $ sudo snap run hello-world
Hello World!

```

**Comment by zigford** [comment]
I'm not sure what changes in the ebuild would be required, but I was able to resolve my problem by adding suid to the snap-confine file in /usr/lib/snapd.
I figured this from reading a bit of the source and confirming by someone posting their directory tree of this directory online, and I could see the suid bit in ls.

**Comment by JamesB192** [comment]
Thank you for finding that. As of today both the release and live versions have snap confine moded 6755.
