### ISSUE TITLE
official overlay?

### ISSUE THREAD

**Issue by prototype99** [JamesB192/JamesB192-overlay#2]
hello, just thought i'd check if you wanted to submit this as an official overlay? you seem to have some solid ebuilds, but as i'm sure is the case for others... i didn't even know this overlay existed!

**Comment by JamesB192** [comment]
No, tahnk you. I am too inclined to put junk into it like the recent addition of broken dev-python/pylint and dev-python/astroid. media-sound/helm has never been properly tested either.

**Comment by sophietheopossum** [comment]
fair enough, might as well close the issue then. just thought i'd check
